name: ESP32 uvc fw build
runs:
  using: "composite"
  steps:
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.3
        target: esp32s3
        path: esp32/uvc