name: Main
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: ESP32 build
        uses: ./esp32/tcp_client/.github/workflows/action.yml